sudo: required

services:
  - docker

env:
  - OWNER=raniemi PROJECT=bintray-erlang-solutions

before_install:
  - ./bin/docker-build

script:
  - ./bin/docker-run "./upload-to-bintray"

notifications:
  recipients:
    - dev@lone-cyprus.com
